# Don't forget to run
#
#     pkg> dev ..
#
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
SimpleKernelRegression = "47c81bad-6c13-54dd-8d7a-198cdd0ce79a"

[compat]
Documenter = "1"
